apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-crb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: daryl-test-pv
    namespace: default
roleRef:
  kind: ClusterRole
  name: pv-access-clusterrole
  apiGroup: rbac.authorization.k8s.io
