apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: pvc-source
  namespace: default
spec:
  serviceAccountName: daryl-test-pv
  mode: Resource
  resources:
    - apiVersion: v1
      kind: PersistentVolumeClaim
    - apiVersion: v1
      kind: PersistentVolume
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
