apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source
  namespace: some-other-namespace
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: sequence
      namespace: some-other-namespace