apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: api-server-source
  namespace: default
spec:
  serviceAccountName: daryl-test-api
  mode: Resource
  resources:
    - apiVersion: v1
      kind: Event
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
