apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    metadata:
      annotations:
        # https://knative.dev/docs/serving/autoscaling/autoscaling-metrics
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"

        # autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        # autoscaling.knative.dev/metric: "cpu"
        # autoscaling.knative.dev/target: "50"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display

---
# This Trigger subscribes to the Broker and will forward all the events that it received to event-display.
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: log-trigger
spec:
  broker: knative-rabbitmq-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
