apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-role
subjects:
  - kind: ServiceAccount
    name: daryl-test-api
