apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pvc
    verbs:
      - get
      - list
      - watch
