apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: KubeletConfiguration
        metadata:
          name: config
        memory: "10Gi"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
