apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: test-api-ping
  namespace: default
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"API_URL": "abc.com","POLL_RATE":"123"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: api-testing
      namespace: default