apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-api-adaptor
spec:
  template:
    spec:
      containers:
        - image: index.docker.io/darylang96/knative-api-adaptor:latest
