apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display2
spec:
  template:
    spec:
      containers:
        - image: hbr01.devnet3.staging/cots/knative/eventing/cmd/event_display:1.7.2