apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription-4-listener
  # Name of the Subscription.
  namespace: default
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: comments-sequence-kn-sequence-4
  subscriber:
    # Required configuration settings for the Subscriber. This is the event Sink that events are delivered to from the Channel.
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display