apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tt
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://172.20.11.183:6443
  project: default
  source:
    path: aaaas/americano-operator/overlay/dev
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/aaaas/manifests
    targetRevision: HEAD