---
apiVersion: v1
kind: Secret
metadata:
  name: first-credentials # IMPORTANT: this Secret name must match .spec.importCredentialsSecret.name field in User object
  namespace: first-namespace
stringData:
  username: first-user
  password: abc123
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: first-user
  namespace: first-namespace
spec:
  tags:
    - management # administrator, management, monitoring, policymaker, impersonator
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample # rabbitmqCluster must exist in the same namespace as this resource
    namespace: default
  importCredentialsSecret:
    name: first-credentials # must match the name of the Secret
