apiVersion: v1
kind: PersistentVolume
metadata:
  name: desktop-pv2
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/daryl" # Replace with your actual Desktop path
