apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: comments-rabbitmq-source
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: rabbitmqcluster-sample
  rabbitmqResourcesConfig:
    parallelism: 10
    exchangeName: "comments-rabbitmq-source"
    queueName: "comments-rabbitmq-source"
  delivery:
    retry: 5
    backoffPolicy: "linear"
    backoffDelay: "PT1S"
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: comments-sequence
