apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: comments-sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        # clean the data
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: knative-data-cleaning-test
    - ref:
        # identify bad words
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: bad-word-filter
    - ref:
        # do sentiment analysis
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: sentiment-analysis-app
    - ref:
        # pass through mongo db adaptor
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: knative-mongo-comments-adaptor
    - ref:
        # store in db
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: knative-mongodb
