apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: api-server-source
  namespace: daryl
spec:
  serviceAccountName: k8s-test
  mode: Reference
  resources:
    - apiVersion: v1
      kind: Event
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: knative-rabbitmq-broker
      namespace: daryl
