apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role
  namespace: daryl
rules:
  - apiGroups:
      - ""
    resources:
      - events
      # - pv
      # - pvc
    verbs:
      - get
      - list
      - watch
